#!/bin/bash -x

set -o errexit
set -o nounset
set -o pipefail

# If a pidfile is still around (for example after a container restart),
# delete it so that docker can start.
rm -rf /var/run/docker.pid

# stop docker daemon on shutdown to avoid loopback leaks
trap 'kill $(cat /var/run/docker.pid)' EXIT

if [ "${LOG:-}" == "file" ]; then
  docker daemon ${DOCKER_DAEMON_ARGS} &>/var/log/docker.log &
else
  docker daemon ${DOCKER_DAEMON_ARGS} &
fi
(( timeout = 60 + SECONDS ))
until docker info >/dev/null 2>&1; do
  if (( SECONDS >= timeout )); then
    echo 'Timed out trying to connect to internal docker host.' >&2
    exit 1
  fi
  sleep 1
done

if [[ "${1:-}" ]]; then
  exec "$@"
else
  exec bash --login
fi

# TBD: default to vfs if overlay isn't available:
# https://github.com/kubernetes/release/pull/86#issuecomment-248185616
