#!/bin/bash

# Copyright 2013-2016 Jérôme Petazzoni, Johan Haleby, lalyos, James Harris,
#                     Michael Elsdörfer, Tony Hesjevik, Esben Haabendal,
#                     Michael A. Smith, Stefan Schimanski, Karl Isenberg,
#                     Alexander Morozov, David Calavera, Sven Dowideit,
#                     Tianon Gravi, Maru Newby
#
# Original sources: https://github.com/jpetazzo/dind
#                   https://github.com/docker/docker/blob/master/hack/dind
#                   https://github.com/marun/dkr-systemd-dind
# Modified to add docker network reservations.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

# Ensure that all nodes in /dev/mapper correspond to mapped devices currently loaded by the device-mapper kernel driver
# TBD: is this necessary?
if [ -e /dev/mapper/control ]; then
    dmsetup mknodes
fi

if [ -d /sys/kernel/security ] && ! mountpoint -q /sys/kernel/security; then
  mount -t securityfs none /sys/kernel/security || {
    echo >&2 'Could not mount /sys/kernel/security.'
    echo >&2 'AppArmor detection and --privileged mode might break.'
  }
fi

# Ensure shared mount propagation to ensure volume mounting works for Kubernetes
mount --make-shared /

# Mount /tmp (conditionally)
if ! mountpoint -q /tmp; then
  mount -t tmpfs none /tmp
fi

exec "$@"
