#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace

if [ "${USE_OVERLAY:-}" = "y" ]; then
  kubelet_override_conf=/etc/systemd/system/docker.service.d/20-overlay.conf
  mkdir -p "$(dirname "${kubelet_override_conf}")"
  # TBD: use overlay2 driver & newer docker
  cat >"${kubelet_override_conf}" <<'EOF'
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon -H fd:// --storage-driver=overlay -g /var/lib/docker2 $DOCKER_EXTRA_OPTS
EOF
  if [ -d "/var/lib/docker_keep" ]; then
      # 'mv /var/lib/docker_keep/* /var/lib/docker2/' was causing
      # 'cannot create hardlink' errors when used with Mac docker
      for filename in /var/lib/docker_keep/*; do
          mv "$filename" /var/lib/docker2/
      done
    rmdir /var/lib/docker_keep
  fi
fi

# wait for systemd to start in the container
(( timeout = 60 + SECONDS ))
until systemctl status >/dev/null 2>&1; do
  if (( SECONDS >= timeout )); then
    echo 'Timed out waiting for systemd.' >&2
    exit 1
  fi
  sleep 1
done

systemctl daemon-reload

if [ "${1:-}" = "docker" ]; then
    systemctl stop docker
fi

for service in "$@"; do
    if ! systemctl start "${service}"; then
        echo >&2 "${service} failed to start. Diagnostics below:"
        systemctl status "${service}"
        exit 1
    fi
done
