#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace

/usr/local/bin/start_services docker kubelet

# start kubeadm init
# FIXME: --hostname-override / --cluster-cidr are already obtained
# in wrapdocker for kubelet config
hostname_override="$(getent hosts $(hostname) | cut -d' ' -f1 | sort -u | tail -1)"
cluster_cidr="$(ip addr show docker0 | grep -w inet | awk '{ print $2; }')"
# --hostname-override=${hostname_override}
# makes no sense because it would be passed to every pod :(
# perhaps should just put all nodes into /etc/hosts on each node(?)
KUBE_HYPERKUBE_IMAGE=${HYPERKUBE_IMAGE} \
  kubeadm "$@"
