#!/bin/bash
# Copyright 2017 Mirantis
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace

echo "Trying to load overlay module (this may fail)" >&2
modprobe overlay || true

storage_opts=
if grep -q '[[:blank:]]overlay[[:blank:]]*' /proc/filesystems; then
    # --storage-opt overlay2.override_kernel_check=true is needed for CentOS systems
    storage_opts="--storage-driver=overlay2 --storage-opt overlay2.override_kernel_check=true"
fi

# FIXME: this fix really concerns kubelet, so perhaps it should go
# into another place
# Kubelet will try to contact GCE metadata server on startup if
# it detects a GCE VM and this breaks kdc on Travis
if [[ $(cat /sys/class/dmi/id/product_name) =~ Google ]]; then
    echo "KDC" >/dmi_product_name
    mount --bind /dmi_product_name /sys/class/dmi/id/product_name
fi

exec /usr/bin/dockerd -H fd:// ${storage_opts} -g /dind/docker "$@"
