#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace

storage_opts=
if grep -q '[[:blank:]]overlay[[:blank:]]*' /proc/filesystems; then
    storage_opts="--storage-driver=overlay2"
fi

exec /usr/bin/dockerd -H fd:// "${storage_opts}" -g /dind/docker "$@"
