#!/bin/bash
# Copyright 2017 Mirantis
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace

# wait for systemd to start in the container
(( timeout = 60 + SECONDS ))
until systemctl status >/dev/null 2>&1; do
  if (( SECONDS >= timeout )); then
    echo 'Timed out waiting for systemd.' >&2
    exit 1
  fi
  sleep 1
done

systemctl daemon-reload

if [ "${1:-}" = "docker" ]; then
    systemctl stop docker
fi

for service in "$@"; do
  if ! systemctl start "${service}"; then
    echo >&2 "${service} failed to start. Diagnostics below:"
    systemctl status "${service}"
    exit 1
  fi
done
